version: "3.9"

services:
  db:
    image: postgres:14.5-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: hackme
      POSTGRES_USER: sanic
      POSTGRES_DB: sanic_db
    restart: always
  server:
    build: .
    command: python server.py
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:

networks:
  default:
    driver: bridge